import React, { useState } from "react";
import axios from "axios";

const SERVER_URL = "http://localhost:5000";

function CloseShippingManifest() {
  const [shippingManifestCode, setShippingManifestCode] =
    useState("");

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState(null);

  // ----------------------------------------------------------
  // Submit
  // ----------------------------------------------------------

  const handleSubmit = async (event) => {
    event.preventDefault();

    setError("");
    setResult(null);

    const manifestCode =
      shippingManifestCode.trim();

    if (!manifestCode) {
      setError(
        "Shipping Manifest Code is required."
      );
      return;
    }

    setLoading(true);

    try {
      const response = await axios.post(
        `${SERVER_URL}/api/uniware/shipping-manifests/close`,
        {
          shippingManifestCode:
            manifestCode,
        }
      );

      setResult(response.data);
    } catch (err) {
      const responseData =
        err.response?.data;

      setError(
        responseData?.message ||
          err.message ||
          "Failed to close shipping manifest."
      );

      if (responseData) {
        setResult(responseData);
      }
    } finally {
      setLoading(false);
    }
  };

  // ----------------------------------------------------------
  // Clear
  // ----------------------------------------------------------

  const handleClear = () => {
    setShippingManifestCode("");
    setError("");
    setResult(null);
  };

  return (
    <div
      style={{
        maxWidth: "1000px",
        margin: "30px auto",
        padding: "24px",
        fontFamily:
          "Arial, Helvetica, sans-serif",
      }}
    >
      <div
        style={{
          background: "#fff",
          border: "1px solid #e5e7eb",
          borderRadius: "12px",
          padding: "28px",
          boxShadow:
            "0 2px 12px rgba(0, 0, 0, 0.08)",
        }}
      >
        {/* Header */}
        <div
          style={{
            marginBottom: "25px",
          }}
        >
          <h2
            style={{
              margin: 0,
              fontSize: "27px",
            }}
          >
            Close Shipping Manifest
          </h2>

          <p
            style={{
              color: "#6b7280",
              marginTop: "8px",
              lineHeight: 1.6,
            }}
          >
            Close an existing Uniware shipping
            manifest after all shipments have
            been added and handed over to the
            shipping provider.
          </p>

          <span
            style={{
              display: "inline-block",
              padding: "6px 10px",
              borderRadius: "5px",
              background: "#dbeafe",
              color: "#1e40af",
              fontSize: "12px",
              fontWeight: 700,
            }}
          >
            TENANT LEVEL — NO FACILITY REQUIRED
          </span>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          <div
            style={{
              padding: "20px",
              background: "#fafafa",
              border:
                "1px solid #e5e7eb",
              borderRadius: "9px",
            }}
          >
            <label
              htmlFor="shippingManifestCode"
              style={{
                display: "block",
                marginBottom: "8px",
                fontWeight: 600,
                fontSize: "14px",
              }}
            >
              Shipping Manifest Code *
            </label>

            <input
              id="shippingManifestCode"
              type="text"
              value={
                shippingManifestCode
              }
              onChange={(event) =>
                setShippingManifestCode(
                  event.target.value
                )
              }
              placeholder="e.g. MANIFEST00001"
              style={{
                width: "100%",
                boxSizing: "border-box",
                padding: "12px",
                border:
                  "1px solid #d1d5db",
                borderRadius: "7px",
                background: "#fff",
                fontSize: "14px",
              }}
            />

            <div
              style={{
                marginTop: "9px",
                color: "#6b7280",
                fontSize: "12px",
              }}
            >
              Enter the shipping manifest code
              generated by Uniware.
            </div>
          </div>

          {/* Actions */}
          <div
            style={{
              display: "flex",
              gap: "12px",
              marginTop: "22px",
            }}
          >
            <button
              type="submit"
              disabled={loading}
              style={{
                padding: "13px 22px",
                border: "none",
                borderRadius: "7px",
                background: "#dc2626",
                color: "#fff",
                fontWeight: 700,
                cursor: loading
                  ? "not-allowed"
                  : "pointer",
                opacity: loading
                  ? 0.7
                  : 1,
              }}
            >
              {loading
                ? "Closing Manifest..."
                : "Close Shipping Manifest"}
            </button>

            <button
              type="button"
              onClick={handleClear}
              style={{
                padding: "13px 22px",
                border:
                  "1px solid #d1d5db",
                borderRadius: "7px",
                background: "#fff",
                cursor: "pointer",
                fontWeight: 600,
              }}
            >
              Clear
            </button>
          </div>
        </form>

        {/* Error */}
        {error && (
          <div
            style={{
              marginTop: "25px",
              padding: "15px",
              background: "#fef2f2",
              border:
                "1px solid #fecaca",
              borderRadius: "8px",
              color: "#b91c1c",
            }}
          >
            <strong>Error:</strong>{" "}
            {error}
          </div>
        )}

        {/* Result */}
        {result && (
          <ManifestCloseResult
            result={result}
          />
        )}
      </div>
    </div>
  );
}

// ============================================================
// Result
// ============================================================

function ManifestCloseResult({ result }) {
  const status =
    result.shippingManifestStatus ||
    {};

  const failedPackages =
    Array.isArray(
      status.failedShippingPackages
    )
      ? status.failedShippingPackages
      : [];

  const errors = Array.isArray(
    result.errors
  )
    ? result.errors
    : [];

  const warnings = Array.isArray(
    result.warnings
  )
    ? result.warnings
    : [];

  return (
    <div
      style={{
        marginTop: "30px",
      }}
    >
      <h3>Close Manifest Result</h3>

      {/* Main status */}
      <div
        style={{
          padding: "18px",
          borderRadius: "9px",
          background:
            result.successful
              ? "#f0fdf4"
              : "#fef2f2",
          border: `1px solid ${
            result.successful
              ? "#bbf7d0"
              : "#fecaca"
          }`,
        }}
      >
        <div
          style={{
            fontSize: "18px",
            fontWeight: 700,
            color:
              result.successful
                ? "#15803d"
                : "#b91c1c",
          }}
        >
          {result.successful
            ? "✓ Manifest Closed Successfully"
            : "✕ Manifest Close Failed"}
        </div>

        <div
          style={{
            marginTop: "8px",
            color: "#374151",
          }}
        >
          {result.message ||
            "N/A"}
        </div>
      </div>

      {/* Summary */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns:
            "repeat(auto-fit, minmax(210px, 1fr))",
          gap: "14px",
          marginTop: "20px",
        }}
      >
        <ResultCard
          label="Manifest Code"
          value={
            result.shippingManifestCode ||
            status.shippingManifestCode
          }
        />

        <ResultCard
          label="Current Status"
          value={
            status.currentStatus
          }
        />

        <ResultCard
          label="Completed"
          value={
            status.completed ===
            undefined
              ? "N/A"
              : status.completed
                ? "Yes"
                : "No"
          }
        />

        <ResultCard
          label="Successful"
          value={
            status.successful ===
            undefined
              ? "N/A"
              : status.successful
                ? "Yes"
                : "No"
          }
        />

        <ResultCard
          label="Progress"
          value={
            status.percentageComplete ===
            undefined
              ? "N/A"
              : `${status.percentageComplete}%`
          }
        />

        <ResultCard
          label="Current Milestone"
          value={
            status.currentMileStone ===
            undefined
              ? "N/A"
              : status.currentMileStone
          }
        />

        <ResultCard
          label="Milestone Count"
          value={
            status.mileStoneCount ===
            undefined
              ? "N/A"
              : status.mileStoneCount
          }
        />

        <ResultCard
          label="Manifest ID"
          value={status.id}
        />
      </div>

      {/* Manifest link */}
      {status.shippingManifestLink && (
        <div
          style={{
            marginTop: "20px",
            padding: "15px",
            background: "#eff6ff",
            border:
              "1px solid #bfdbfe",
            borderRadius: "8px",
          }}
        >
          <strong>
            Shipping Manifest Link:
          </strong>{" "}

          <a
            href={
              status.shippingManifestLink
            }
            target="_blank"
            rel="noreferrer"
          >
            Open Manifest
          </a>
        </div>
      )}

      {/* Failed packages */}
      {failedPackages.length > 0 && (
        <div
          style={{
            marginTop: "22px",
            padding: "18px",
            background: "#fef2f2",
            border:
              "1px solid #fecaca",
            borderRadius: "8px",
          }}
        >
          <h4
            style={{
              marginTop: 0,
            }}
          >
            Failed Shipping Packages
          </h4>

          <div
            style={{
              overflowX: "auto",
            }}
          >
            <table
              style={{
                width: "100%",
                borderCollapse:
                  "collapse",
              }}
            >
              <thead>
                <tr>
                  <th style={thStyle}>
                    Package Code
                  </th>

                  <th style={thStyle}>
                    Sale Order
                  </th>

                  <th style={thStyle}>
                    Failure Reason
                  </th>

                  <th style={thStyle}>
                    Cancelled
                  </th>
                </tr>
              </thead>

              <tbody>
                {failedPackages.map(
                  (
                    item,
                    index
                  ) => (
                    <tr
                      key={index}
                    >
                      <td
                        style={
                          tdStyle
                        }
                      >
                        {item.code ||
                          "N/A"}
                      </td>

                      <td
                        style={
                          tdStyle
                        }
                      >
                        {item.saleOrderCode ||
                          "N/A"}
                      </td>

                      <td
                        style={
                          tdStyle
                        }
                      >
                        {item.failureReason ||
                          "N/A"}
                      </td>

                      <td
                        style={
                          tdStyle
                        }
                      >
                        {item.cancelled ===
                        undefined
                          ? "N/A"
                          : item.cancelled
                            ? "Yes"
                            : "No"}
                      </td>
                    </tr>
                  )
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Errors */}
      {errors.length > 0 && (
        <div
          style={{
            marginTop: "22px",
            padding: "18px",
            background: "#fef2f2",
            border:
              "1px solid #fecaca",
            borderRadius: "8px",
          }}
        >
          <h4
            style={{
              marginTop: 0,
            }}
          >
            Uniware Errors
          </h4>

          {errors.map(
            (item, index) => (
              <div
                key={index}
                style={{
                  padding:
                    "10px 0",
                  borderBottom:
                    "1px solid #fee2e2",
                }}
              >
                <div>
                  <strong>
                    Code:
                  </strong>{" "}
                  {item.code ??
                    "N/A"}
                </div>

                <div>
                  <strong>
                    Field:
                  </strong>{" "}
                  {item.fieldName ||
                    "N/A"}
                </div>

                <div>
                  <strong>
                    Message:
                  </strong>{" "}
                  {item.message ||
                    item.description ||
                    "N/A"}
                </div>
              </div>
            )
          )}
        </div>
      )}

      {/* Warnings */}
      {warnings.length > 0 && (
        <div
          style={{
            marginTop: "22px",
            padding: "18px",
            background: "#fffbeb",
            border:
              "1px solid #fde68a",
            borderRadius: "8px",
          }}
        >
          <h4
            style={{
              marginTop: 0,
            }}
          >
            Uniware Warnings
          </h4>

          {warnings.map(
            (item, index) => (
              <div
                key={index}
                style={{
                  marginBottom:
                    "8px",
                }}
              >
                <strong>
                  {item.code ??
                    "Warning"}
                  :
                </strong>{" "}
                {item.message ||
                  item.description ||
                  "N/A"}
              </div>
            )
          )}
        </div>
      )}

      {/* Raw response */}
      <details
        style={{
          marginTop: "22px",
        }}
      >
        <summary
          style={{
            cursor: "pointer",
            fontWeight: 600,
          }}
        >
          Raw Uniware Response
        </summary>

        <pre
          style={{
            marginTop: "12px",
            padding: "16px",
            background: "#111827",
            color: "#e5e7eb",
            borderRadius: "8px",
            overflowX: "auto",
            fontSize: "13px",
          }}
        >
          {JSON.stringify(
            result,
            null,
            2
          )}
        </pre>
      </details>
    </div>
  );
}

// ============================================================
// Result card
// ============================================================

function ResultCard({
  label,
  value,
}) {
  return (
    <div
      style={{
        padding: "14px",
        background: "#f9fafb",
        border:
          "1px solid #e5e7eb",
        borderRadius: "7px",
      }}
    >
      <div
        style={{
          fontSize: "12px",
          color: "#6b7280",
          marginBottom: "5px",
        }}
      >
        {label}
      </div>

      <div
        style={{
          fontWeight: 600,
          wordBreak:
            "break-word",
        }}
      >
        {value ===
          undefined ||
        value === null ||
        value === ""
          ? "N/A"
          : value}
      </div>
    </div>
  );
}

const thStyle = {
  textAlign: "left",
  padding: "11px",
  background: "#f3f4f6",
  borderBottom:
    "1px solid #d1d5db",
  fontSize: "13px",
};

const tdStyle = {
  padding: "11px",
  borderBottom:
    "1px solid #e5e7eb",
  fontSize: "13px",
};

export default CloseShippingManifest;